# Workflow name
name: Hello Dosto

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

# these are Jobs inside the workflow
jobs:
  # thisis the name of the Job 
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to users
        run: echo "Hello Dosto"

      - name: Say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubunutu-latest
    steps:
      - name: show what is  the version of python, docker, etc
        run: docker --version && python --version
